-- AlterTable
-- Existing plaintext keys cannot be converted to hashes; any existing API keys
-- are deleted here and must be regenerated by the user.
DELETE FROM "ApiKey";

ALTER TABLE "ApiKey" DROP COLUMN "key",
ADD COLUMN     "keyHash" TEXT NOT NULL,
ADD COLUMN     "keyPrefix" TEXT NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "ApiKey_keyHash_key" ON "ApiKey"("keyHash");
